version: '3.0'
services:
  mockserver:
    build: ./mocks
    ports:
    - "8081:8081"
    volumes:
    - $PWD/mocks/config:/mocks
  app:
    build: .
    ports:
      - "8080:8080"
  test:
    image: cypress/included:4.4.1
    depends_on:
      - app
      - mockserver
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - $PWD/e2e:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix
    entrypoint: cypress open -P /e2e