version: '3.0'
services:
  mockserver:
    build: ./mocks
    ports:
    - "8081:8081"
    volumes:
    - $PWD/mocks/config:/mocks
  app:
    build: .
    ports:
      - "8080:8080"
  test:
    image: cypress/included:4.4.1
    depends_on:
      - app
      - mockserver
    volumes:
      - $PWD/e2e:/e2e
    command: cypress run -P /e2e